feat!(validator): rename output submitter and challenger flags
kroma-network/kroma pull request #114
Opened 2023-07-11 10:00 UTC by 0xHansLee

Renamed two validator flags for consistency and readability: 
`VALIDATOR_OUTPUT_SUBMITTER_ENABLED` and `VALIDATOR_CHALLENGER_ENABLED`, both are required.

At first, we named the flags with `*_DISABLED`. If no value is set, it was to turn on the output submitter and challenger by default.

With this renaming, we should provide a sample `.env` file with default value of `true` for both flags for guide of running Kroma node.

2023-07-11 13:14 UTC, chokobole requested changes
I think this should be committed with the commit type 'feat' and it should support all old flags for backward compatibility. Additionally, the help message should indicate that they are going to be deprecated.

2023-07-11 23:07 UTC, 0xHansLee commented
> I think this should be committed with the commit type feat and it should support all old flags for backward compatibility. Additionally, the help message should indicate that they are going to be deprecated.

Right. Thank you for pointing it out. We should support backward compatibility. I'll restore the old flags and mark `deprecated` as you suggested.

2023-07-12 02:40 UTC, 0xHansLee commented
As we discussed offline, these changes will be included in the next release without backward compatibility.
We should keep in mind that the guides would also be provided accordingly, so I added `!` in the commit.

2023-07-12 04:59 UTC, Pangssu approved these changes
LGTM

2023-07-12 05:22 UTC, seolaoh commented on components/validator/flags/flags.go
> +		Required: true,
Please move the required flags above `// Optional flags`.

2023-07-12 05:22 UTC, seolaoh commented on components/validator/flags/flags.go
> +		Required: false,
Don't need this line because `Required` default value is `false`.

2023-07-12 05:22 UTC, seolaoh commented on components/validator/flags/flags.go
> +	OutputSubmitterEnabledFlag,
Please move these required flags to `requiredFlags`, and move `ProverGrpcFlag` to here.

2023-07-12 05:22 UTC, seolaoh commented on components/validator/config.go
> +		OutputSubmitterEnabled:       ctx.GlobalBool(flags.OutputSubmitterEnabledFlag.Name),
Please move these required flags above `// Optional Flags`, and move `ProverGrpc` here.

2023-07-12 05:22 UTC, seolaoh commented on components/validator/config.go
>  		return nil, errors.New("ProverGrpc is required but given empty")
```suggestion
		return nil, errors.New("ProverGrpc is required when challenger enabled, but given empty")
```

2023-07-12 05:22 UTC, seolaoh commented on e2e/setup.go
> +		OutputSubmitterEnabled:       true,
We can remove `ProverGrpc` of asserter.

2023-07-12 05:22 UTC, seolaoh commented on ops-devnet/docker-compose.yml
> +      VALIDATOR_CHALLENGER_ENABLED: "false"
We need to add `VALIDATOR_OUTPUT_SUBMITTER_ENABLED` to `kroma-validator` also.

2023-07-12 05:22 UTC, seolaoh commented on ops-devnet/docker-compose.yml
> +      VALIDATOR_OUTPUT_SUBMITTER_ENABLED: "false"
We need to add `VALIDATOR_CHALLENGER_ENABLED` to `kroma-challenger` also.

2023-07-12 07:13 UTC, 0xHansLee commented
@seolaoh Thank you. I applied all your comments. Please review again.

2023-07-12 07:24 UTC, kangsorang approved these changes
lgtm

2023-07-12 07:54 UTC, seolaoh approved these changes
LGTM

2023-07-13 12:25 UTC, chokobole approved these changes
LGTM

2023-07-13 13:20 UTC, merged