fix: minor typos
kroma-network/kroma pull request #231
Opened 2023-12-07 04:24 UTC by tudorpintea999

Hello
I fixed some typos in the docs,
Hope it helps,
Br,
Tudor.

2023-12-15 02:51 UTC, 0xHansLee requested changes
Thank you for your contributions!

First of all, we are trying to minimize the differences from Optimism, so I suggested some changes for this.

2023-12-15 02:51 UTC, 0xHansLee commented on specs/derivation.md
> +the [rollup node][g-rollup-node], both in sync mode, and in sequencer mode (where derivation acts as a sanity check
```suggestion
the [rollup node][g-rollup-node], both in validator mode, and in sequencer mode (where derivation acts as a sanity check
```

2023-12-15 02:51 UTC, 0xHansLee commented on specs/derivation.md
> +the [rollup node][g-rollup-node], both in sync mode, and in sequencer mode (where derivation acts as a sanity check
And also, please change the word `syncer` in L660 to `validator`.

2023-12-15 02:51 UTC, 0xHansLee commented on specs/derivation.md
> +All frames in a batcher transaction must be parsable. If any one frame fails to parse, then all frames in the
For the same words with Optimism. 
https://github.com/ethereum-optimism/optimism/blob/b4c39a90f996b7131a9d03c7937e31e38445f22d/specs/derivation.md?plain=1#L310
```suggestion
All frames in a batcher transaction must be parsable. If any one frame fails to parse, the all frames in the
```

2023-12-15 02:51 UTC, 0xHansLee commented on specs/exec-engine.md
> +This document outlines the modifications, configuration and usage of an L1 execution engine for L2.
Same here. 
https://github.com/ethereum-optimism/optimism/blob/b4c39a90f996b7131a9d03c7937e31e38445f22d/specs/exec-engine.md?plain=1#L28
```suggestion
This document outlines the modifications, configuration and usage of a L1 execution engine for L2.
```

2024-04-03 07:47 UTC, Pangssu commented
Moved specifications to https://github.com/kroma-network/kroma-specs

2024-04-03 07:47 UTC, closed without merging