chore: skip transactions root validation
kroma-network/kroma pull request #67
Opened 2023-06-15 09:32 UTC by chokobole

2023-06-15 09:33 UTC, chokobole commented
This should be merged after https://github.com/kroma-network/kroma/pull/65

2023-06-16 09:34 UTC, 0xHansLee approved these changes

2023-06-19 07:17 UTC, Pangssu approved these changes
LGTM

2023-06-19 07:33 UTC, 0xHansLee requested changes

2023-06-19 07:33 UTC, 0xHansLee commented on components/node/eth/output.go
> +		ParentHash:       o.BlockRef.ParentHash,
You need to update as mentioned before.

2023-06-19 08:59 UTC, 0xHansLee approved these changes

2023-06-19 09:17 UTC, 0xHansLee commented
@chokobole Please check the conflict in `spec/challenge.md` once again 😃

2023-06-20 10:19 UTC, seolaoh approved these changes
LGTM

2023-06-21 16:01 UTC, Pangssu approved these changes
Lgtm

2023-06-21 16:01 UTC, merged